---
- hosts: all
  tasks:
    - name: hostname
      debug: var=ansible_hostname
    - name: date and time
      vars:
        msg: |
          Date: {{ ansible_date_time.date }}
          Timezone: {{ ansible_date_time.tz }}
      debug:
        msg: "{{ msg.split('\n') }}"
    - name: network info
      vars:
        msg: |
          All Interface List: {{ ansible_interfaces }}
          All IP: {{ ansible_all_ipv4_addresses }}
          Gateway: {{ ansible_default_ipv4.gateway }}
      debug:
        msg: "{{ msg.split('\n') }}"
    - name: OS and Kernel info
      vars:
        msg: |
          Distribution: {{ ansible_distribution }}
          Distribution Version: {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
      debug:
        msg: "{{ msg.split('\n') }}"
    - name: HW info
      vars:
        msg: |
          CPU: {{ ansible_processor }}
          CPU Core: {{ ansible_processor_cores }}
          RAM: {{ ansible_memtotal_mb }}
          SWAP: {{ ansible_memory_mb.swap.total }}
      debug:
        msg: "{{ msg.split('\n') }}"
    - name: file system
      command: df -h
      register: fs
    - debug:
        var: fs.stdout_lines
    - name: Installed Packages
      yum:
        list: installed
      register: pck
    - debug:
        var: pck.results
    - name: fstab entries
      command: cat /etc/fstab
      register: fstab_entry
    - debug:
        var: fstab_entry.stdout_lines
    - name: resolv.conf entries
      command: cat /etc/resolv.conf
      register: resolv_entry
    - debug:
        var: resolv_entry.stdout_lines
    - name: hosts file entry
      command: cat /etc/hosts
      register: hosts_entry
    - debug:
        var: hosts_entry.stdout_lines
    - name: Copy System details into a file
      copy:
        dest: "playbook"
        content: |
          hostname: {{ansible_hostname}}
          Timezone: {{ ansible_date_time.tz }}
          All Interface List: {{ ansible_interfaces }}
          All IP: {{ ansible_all_ipv4_addresses }}
          Gateway: {{ ansible_default_ipv4.gateway }}
          Eth0 MAC: {{ ansible_eth0.macaddress }}
          Distribution: {{ ansible_distribution }}
          Distribution Version: {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}
          CPU: {{ ansible_processor }}
          CPU Core: {{ ansible_processor_cores }}
          RAM: {{ ansible_memtotal_mb }}
          SWAP: {{ ansible_memory_mb.swap.total }}
          File System: {{ fs.stdout_lines }}
          Installed Packages: {{ pck.results }}
          Fstab Entries: {{ fstab_entry.stdout_lines }}
          Resolv Entries: {{ resolv_entry.stdout_lines }}
          Hosts Entries: {{ hosts_entry.stdout_lines }}
    - name: Send Emails
      mail:
        host: smtp.gmail.com
        port: 587
        secure: starttls
        username: email
        password: password
        to: email
        subject: Ansible Playbook Report
        body: Server report has been attached
        attach: playbook
